### ISSUE TITLE
Export installable .apk 

### ISSUE THREAD

**Issue by LaKrieger** [neuroinfo-os/Traumschreiber#15]
At the moment the app can only be installed via Android Studio when the phone is in Developer Mode.

**Comment by mvidaldp** [comment]
Done! https://github.com/neuroinfo-os/Traumschreiber/releases/tag/v1.0-alpha_new

**Comment by mvidaldp** [comment]
Done! https://github.com/neuroinfo-os/Traumschreiber/releases/tag/v1.0-alpha_new
