### ISSUE TITLE
Change the Gain from 1 to 8

### ISSUE THREAD

**Issue by LaKrieger** [neuroinfo-os/Traumschreiber#16]
Changing the gain from 1 to 8 and test whether it makes a difference. See Page 64 of ADC manual (and Gordon's message on Slack-General)

**Comment by mvidaldp** [comment]
It works with the old traumschreiber, not yet with the new one.

**Comment by paria-samimi** [comment]
the gain has been changed from 1 to 8 but the result of Sanity check with the new gain is meaningless. So, we still have some issues in this part.
