### ISSUE TITLE
Recording different Gain Settings

### ISSUE THREAD

**Issue by LaKrieger** [neuroinfo-os/Traumschreiber#24]
Recording Data in App not possible when Gain other than 1 is selected (red recording button cannot be selected). Changing Gain back to 1 does not solve the issue (recording still not possible then)

**Comment by mvidaldp** [comment]
@denizmguen fixed it on https://github.com/adrocampos/EEG-Droid/commit/c4e0b09fdb6ae849201bc92da91906f0d9fecc9e
