### ISSUE TITLE
Battery did not load after fully discharged

### ISSUE THREAD

**Issue by gordonpipa** [neuroinfo-os/Traumschreiber#4]
The battery did nit start charging after the battery was fully discharged.
Is solved in Board Design 2.91
In 2.8 the R68 was connected to VBAT instead of VIN. 
In 2.91 R68  is no connected to VIN.

**Comment by gordonpipa** [comment]
![designchange](https://user-images.githubusercontent.com/34439167/83352408-67f1dc80-a34b-11ea-9cee-5dfb1c631bda.PNG)

Is solved in Board Design 2.91
In V2.8 the R68 was connected to VBAT instead of VIN.
In V2.91 R68 is no connected to VIN.

**Comment by gordonpipa** [comment]
do redign of open wire in V2.91

**Comment by pariasamimi** [comment]
both of the resistors are changed

**Comment by pariasamimi** [comment]
you actually changed the connection of R63, not R68.  You did right in the board just wrote the wrong name here.

**Comment by gordonpipa** [comment]
Can you add this informtion in the issues on github please 

 

Did you make progress with getting into the programming of the the device ? 

 

 

---------------------------------------------------------------------------------------------------------------

Professor and Chair of the Neuroinformatics Department

Dr. rer. nat. Gordon Pipa

Institute of Cognitive Science, Room 50/218

University of Osnabrueck

Wachsbleiche 27, 49090 Osnabrück, Germany 

 

tel.                    +49 (0) 541-969-2277    

fax (private).  +49 (0) 5405- 500 80 98

home office.  +49 (0) 5405- 500 90 95

e-mail:               gpipa@uos.de <mailto:gpipa@uos.de> 

webpage:         http://www.ni.uos.de <http://www.ni.uos.de/> 

research gate:  <https://www.researchgate.net/profile/Gordon_Pipa/?ev=prf_act> https://www.researchgate.net/profile/Gordon_Pipa/?ev=prf_act 

linkedin:            https://de.linkedin.com/in/gordon-pipa-47771539

 

Personal Assistent and Secretary of the Neuroinformatic lab:

Anna Jungeilges 

Tel. +49 (0)541 969-2390

Fax +49 (0)541 969-2246

Email:  <mailto:anna.jungeilges@uni-osnabrueck.de> anna.jungeilges@uni-osnabrueck.de

visit us on 

 <http://www.facebook.com/CognitiveScienceOsnabruck> http://www.facebook.com/CognitiveScienceOsnabruck 

https://twitter.com/#!/CogSciUOS

 

Von: pariasamimi [mailto:notifications@github.com] 
Gesendet: Dienstag, 2. Juni 2020 20:13
An: neuroinfo-os/Traumschreiber <Traumschreiber@noreply.github.com>
Cc: gordonpipa <gpipa@uos.de>; Assign <assign@noreply.github.com>
Betreff: Re: [neuroinfo-os/Traumschreiber] Battery did not load after fully discharged (#4)

 

you actually changed the connection of R63, not R68. You did right in the board just wrote the wrong name here.
