### ISSUE TITLE
Traumschreiber code should not crash

### ISSUE THREAD

**Issue by LaKrieger** [neuroinfo-os/Traumschreiber#9]
it crashes

**Comment by t-dreamer** [comment]
when trying to send compressed AD data the program crashes after a few seconds. with dummy data it works fine, however.

**Comment by LaKrieger** [comment]
Any updates on the issue?

**Comment by t-dreamer** [comment]
not really, no. I still could not figure out, what is causing those crashes, but I have some hints that point in the direction cpu load (which is unfortunately not observable directly).
